services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    #restart: always

  api-limit-test:
    image: "jhawk7/go-api-limit-test"
    build: .
    ports:
      - "8888:8888"
    #restart: always
    depends_on:
      - redis